name: Adventure Collective
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8486914203967899
title: Adventure Collective
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74674759-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6d3d08'
    - '#de903d'
    - '#d9e0e6'
    - '#281301'
    - '#7290aa'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
