name: Adventure-Collective
favicon: null
layout_spectrum: 0.2708884277381003
typography_spectrum: 0.8486914203967899
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.9793818260077387
  lightness: 0.26677869469858706
  saturation: 0.9504912050906569
  rhythmicContrast: 0.29097023839131
purpose: []
